config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'sessions#new'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  get 'e401' => 'application#unauthorized_view_render'

  namespace :admin do
    get 'home' => 'home#index'

    resources :reports do
      collection do
        get 'get_reports' => 'reports#get_reports'
      end
    end
    resources :users do
      collection do
        get 'get_users' => 'users#get_users'
      end
    end
  end

  namespace :api, path: '/', defaults: {format: :json} do
    namespace :v1 do

      resources :users, only: [:create, :show] do
        collection do
          post 'login'
        end
      end

      resources :reports
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
end

app/models/priority.rb
class Priority < ApplicationRecord
  has_many :reports

  UNASSIGNED = 1
  LOW = 2
  HALF = 3
  HIGH = 4
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  belongs_to :priority
  belongs_to :status_report

  mount_uploader :image, ImageUploader

  validates :title, :description, :latitude, :longitude, :user, presence: true
end

app/models/state.rb
class State < ApplicationRecord
end

app/models/status_report.rb
class StatusReport < ApplicationRecord
  has_many :reports

  PENDING = 1
  IN_PROCESS = 2
  ATTENDED = 3
end

app/models/type_user.rb
class TypeUser < ApplicationRecord
  has_many :users

  ADMIN = 1
  CLIENT = 2
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :type_user

  validates :email, presence: true, uniqueness: true
  validates :username, uniqueness: true, if: -> { username.present? }
  validates :password, presence: true, :on => :create
  validates :password, presence: true, if: :change_password

  before_create :password_hash
  before_update :password_hash, if: :change_password
  attr_accessor :change_password

  def clearance_levels
    self.type_user.name
  end

  def password_hash
    var = if password.present?
            self.password_salt = BCrypt::Engine.generate_salt
            self.password = BCrypt::Engine.hash_secret(password, password_salt)
          end
    var
  end

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
  let :ADMIN, :all

  def index
  end
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < ApplicationController
  let :ADMIN, :all
  before_action :set_report, only: [:show, :update]
  skip_before_action :verify_authenticity_token

  def index
  end

  def show
    render json: {report: @report.as_json(include: :user)}
  end

  def update
    @report.status_report_id = params[:status_report_id]
    @report.priority_id = params[:priority_id]
    if @report.save
      render json: {success: true}, status: :ok
    else
      render json: {errors: @report.errors.full_messages}, status: :unprocessable_entity
    end
  end

  def get_reports
    render json: { reports: Report.all.as_json }
  end

  private

  def set_report
    @report = Report.find(params[:id])
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  let :ADMIN, :all
  skip_before_action :verify_authenticity_token

  def index
  end

  def get_users
    render json: { users: User.all.as_json(include: :type_user) }
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  let :all, :all
  before_action :set_user, only: [:show]
  skip_before_action :verify_authenticity_token

  def show
    render json: {user: @user.as_json(except: [:password, :password_salt, :type_user_id, :updated_at])}
  end

  def create
    user = User.new(user_params)
    user.type_user = TypeUser.find(TypeUser::CLIENT)

    if user.save
      render json: {
        success: true, user: user.as_json(
          except: [:id, :password, :password_salt, :created_at, :updated_at, :type_user_id]
        )
      }, status: :created
    else
      render json: {errors: user.errors.full_messages},
             status: :unprocessable_entity
    end
  end

  def login
    user = User.authenticate(params[:email], params[:password])
    if user && user.type_user.id == TypeUser::CLIENT
      render json: {success: true, user: user.as_json(except: [:password, :password_salt])}, status: :ok
    else
      render json: {success: false, error: 'El usuario no existe o las credenciales son invalidas.'}, status: :ok
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :password, :name, :lastname,
                                 :email, :dependence, :job, :phone_number)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  lock_access
  let :all
  layout :get_layout
  include SessionsHelper

  def unauthorized_access_redirection_path
    # Ensure an array of symbols
    if current_user.nil?
      login_path
    else
      clearance_levels = Array(current_user.clearance_levels).map(&:to_sym)
      return e401_path if clearance_levels.include?(:ADMIN)
    end
  end

  def unauthorized_view_render
    render 'errors/401', layout: false
  end

  private

  def get_layout
    my_class_name = self.class.name
    if my_class_name.index("::").nil?
      layout = "application"
    else
      layout = my_class_name.split("::").first.downcase
    end
    layout
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  let :all, :all
  include SessionsHelper

  def new
    if logged_in?
      enter
    else
      render :action => 'new', :layout => false
    end
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user && user.type_user.id == TypeUser::ADMIN
      log_in user
      enter
    else
      flash[:notice] = 'Correo electrónico o contraseña incorrectos'
      render :action => 'new', :layout => false
    end
  end

  def destroy
    log_out if logged_in?
    flash[:notice] = nil
    redirect_to login_path
  end
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin/reports_helper.rb
module Admin::ReportsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def logged_in?
    !current_user.nil?
  end

  def current_user
    user_id = session[:user_id]
    @current_user ||= User.find_by(id: user_id)
  end

  def log_in(user)
    session[:user_id] = user.id
    session[:user_role] = user.type_user.name
    current_user
  end

  def log_out
    session.delete(:user_id)
    session.delete(:user_role)
    @current_user = nil
  end

  def enter
    if administrator?
      redirect_to admin_home_path
    end
  end

  def administrator?
    current_user.type_user.id == TypeUser::ADMIN
  end
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css"/>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"/>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css"/>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <%= stylesheet_link_tag params[:controller], :media => "all", 'data-turbolinks-track': 'reload' if ::Rails.application.assets.find_asset("#{params[:controller]}.css") %>
  <%= javascript_include_tag params[:controller], 'data-turbolinks-track' => 'reload' if ::Rails.application.assets.find_asset("#{params[:controller]}.js") %>

  <script defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDOAR42pYBEc_6YAChtbLi3-9Kmgh7Pp0M"></script>
</head>

<body ng-app="AdminModule">
<div class="page-wrapper">
  <!-- HEADER MOBILE-->
  <header class="header-mobile d-block d-lg-none">
    <div class="header-mobile__bar">
      <div class="container-fluid">
        <div class="header-mobile-inner">
          <a class="logo mx-auto" href="<%= admin_home_path %>">
            <img src="<%= image_url('logo.png') %>" width="130" alt="CoolAdmin" />
          </a>
          <button class="hamburger hamburger--slider" type="button">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
          </button>
        </div>
      </div>
    </div>
    <nav class="navbar-mobile">
      <div class="container-fluid">
        <ul class="navbar-mobile__list list-unstyled">
          <li>
            <a href="<%= admin_home_path %>">
              <i class="fas fa-home"></i>Inicio</a>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <!-- END HEADER MOBILE-->

  <!-- MENU SIDEBAR-->
  <aside class="menu-sidebar d-none d-lg-block">
    <div class="logo">
      <a href="<%= admin_home_path %>">
        <img src="<%= image_url('logo.png') %>" width="160" alt="Cool Admin" />
      </a>
    </div>
    <div class="menu-sidebar__content js-scrollbar1">
      <nav class="navbar-sidebar">
        <ul class="list-unstyled navbar__list">
          <li class="<%= controller.controller_name == 'home' ? 'active' : '' %>">
            <a href="<%= admin_home_path %>">
              <i class="fas fa-home"></i>Inicio</a>
          </li>
          <li class="<%= controller.controller_name == 'reports' ? 'active' : '' %>">
            <a href="<%= admin_reports_path %>">
              <i class="fas fa-bell"></i>Reportes</a>
          </li>
          <li class="<%= controller.controller_name == 'users' ? 'active' : '' %>">
            <a href="<%= admin_users_path %>">
              <i class="fas fa-user"></i>Usuarios</a>
          </li>
        </ul>
      </nav>
    </div>
  </aside>
  <!-- END MENU SIDEBAR-->

  <!-- PAGE CONTAINER-->
  <div class="page-container">
    <!-- HEADER DESKTOP-->
    <header class="header-desktop">
      <div class="section__content section__content--p30">
        <div class="container-fluid">

          <div class="header-wrap">
            <div class="header-button ml-auto my-auto">
              <div class="account-wrap ml-auto">
                <div class="account-item clearfix js-item-menu">
                  <div class="image">
                    <img src="<%= image_url('icon/avatar-default.jpg') %>" alt="<%= @current_user.name+' '+@current_user.lastname  %>" />
                  </div>
                  <div class="content">
                    <a class="js-acc-btn" href="javascript:void(0)"><%= @current_user.name+' '+@current_user.lastname  %></a>
                  </div>
                  <div class="account-dropdown js-dropdown">
                    <div class="info clearfix">
                      <div class="image">
                        <a href="#">
                          <img src="<%= image_url('icon/avatar-default.jpg') %>" alt="<%= @current_user.name+' '+@current_user.lastname  %>" />
                        </a>
                      </div>
                      <div class="content">
                        <h5 class="name">
                          <a href="#"><%= @current_user.name+' '+@current_user.lastname  %></a>
                        </h5>
                        <span class="email"><%= @current_user.email %></span>
                      </div>
                    </div>
                    <!-- div class="account-dropdown__body">
                      <div class="account-dropdown__item">
                        <a href="#">
                          <i class="zmdi zmdi-account"></i>Account</a>
                      </div>
                      <div class="account-dropdown__item">
                        <a href="#">
                          <i class="zmdi zmdi-settings"></i>Setting</a>
                      </div>
                      <div class="account-dropdown__item">
                        <a href="#">
                          <i class="zmdi zmdi-money-box"></i>Billing</a>
                      </div>
                    </div -->
                    <div class="account-dropdown__footer">
                      <a href="<%= logout_path %>">
                        <i class="zmdi zmdi-power"></i>Salir</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
    </header>
    <!-- HEADER DESKTOP-->

    <!-- MAIN CONTENT-->
    <div class="main-content">
      <div class="section__content section__content--p30">
        <div class="container-fluid">
          <%= yield %>
        </div>
      </div>
    </div>
    <!-- END MAIN CONTENT-->
    <!-- END PAGE CONTAINER-->
  </div>

</div>

</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MukuyWeb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>